### ISSUE TITLE
Server crash with CraftedCore but without mods dependent on it

### ISSUE THREAD

**Issue by Omnimetatron** [ToCraft/craftedcore#1]
https://gist.github.com/Omnimetatron/bd03fe93bbb70de114b7026efe5f180f

Testing on MC 1.20.2 NeoForge 20.2.86 CraftedCore 1.2.3

Server crash when attempting to join world.

**Comment by ToCraft** [comment]
Thanks for reporting, I removed the version from curseforge & modrinth again.
I still don't know why it crashed but I think it's something NeoForge changed compared to Legacy Forge...

**Comment by ToCraft** [comment]
Alright, I just found out that this only occurs if no mod depends on craftedcore. I'll try to fix this asap.

**Comment by ToCraft** [comment]
I fixed this with 3677b639ddaae5eab2079effc0f3eb663a1b78e5 and it'll be implemented as of v1.3
