### ISSUE TITLE
[Bug/Question // 1.18.2 - 4.2.2] Air Bar Depletes Faster than Normal with Mod Enabled

### ISSUE THREAD

**Issue by FocalFlare** [ToCraft/craftedcore#10]
### Mod loader

Forge

### Minecraft version

1.18.2

### CraftedCore version

4.2.2

### Modloader version

40.2.21

### The latest.log file

_(No relevant latest.log file to go with this, but I can re-test this with the mod enabled so I can add one in if needed.)_

### [TL;DR] Rate of air depletion and drowning are both faster than normal with CraftedCore enabled. This mod incurred no crashes.
_Recently I discovered that while I'm under any body of water, I've started to take damage quickly after 10 seconds of being in the water, which is odd because I should only start taking damage after 20 seconds of underwater time._

_This was incredibly odd as I'd suspect that I have some mod installed that alters the time it takes for me to start drowning after x seconds, but I looked through my mods and none of their names even sound like any mod that does such. But regardless, I lose air and start drowning afterward every half second instead of every second, which is not normal whatsoever._

_I knew this had to be a mod or datapack I had active which was causing this--as suggested by someone from another server which I asked about this in, so I looked in my recent world's datapack folder to there only being 3 datapacks I remember adding in. None of them modify air depletion and drowning rates. Testing this in one of my test worlds, it turns out it wasn't just that world and it wasn't a datapack and instead a mod I have active. I went into a hole I made in the ground and filled it with water and dove into it to see that my air bar went from 20 to 0 bubbles in only 10 seconds and my HP decreased by half a second._

_With that, I tested this again just now but this time without this mod, and I'm back to losing air and HP underwater every second, which made me think that this mod was altering something regarding the player's air in the water._

_**So my question is this: is this intentional? Was this mod--despite it being a library mod for other mods--supposed to make my air bar deplete faster than normal while I'm in any body of water?**_

### Steps to reproduce

1. Enable the mod.
2. Load into any world.
3. Sit in any body of water.
4. ???
5. Profit (watch the air bar deplete faster than normal)

### Other

_I checked the JSON config file for this mod and did not see any entry for anything about air (or oxygen):_
![image](https://github.com/ToCraft/craftedcore/assets/78162943/f3a9ebac-f310-46db-96ab-74d650f0e774)

_I also checked the NBT data of my worlds this was occurring in, only to see nothing of avail._

**Comment by ToCraft** [comment]
Fixed as of 314535fdeb25529ffc7ae65cea28c53cfc433124. I'm sorry for the bug.
