### ISSUE TITLE
minecraft forge version of craftedcore 4.2.2 doesn't exist

### ISSUE THREAD

**Issue by eligarner23** [ToCraft/craftedcore#11]
### Mod loader

Forge

### Minecraft version

1.20.6

### CraftedCore version

4.2.2

### Modloader version

50.0.19

### The latest.log file

[latest.log](https://github.com/ToCraft/craftedcore/files/15382080/latest.log)

### Issue description

hi ok so i am having trouble running minecraft 1.20.6 with craftedcore 4.1 it just crashes once the game starts up the mods i am trying to apply to minecraft forge 1.20.6 are remorphed and woodwalkers so i was wanting to see if an forge version of craftedcore 4.2.2 is in the works or not, **NOT NeoForge i despise that modloader besides a version for it is already out.**

### Steps to reproduce

1. apply mods craftedcore 4.1 and mods specified above
2. Start Minecraft Forge 1.20.6
3. and the game should show a screen saying that **craftedcore 4.2 Only is supported**
4. as well as archetecture api but that isn't important that can still work on FML 1.20.6

### Other

the mods i am trying to play with are remorphed and woodwalkers/walkers.

**Comment by ToCraft** [comment]
Yeah, there are some errors with compiling Forge mods for 1.20.6. I hope they're fixed until the next update. (It's caused by some background software I can't affect that easily).

**Comment by eligarner23** [comment]
well i tried installing architectury api but it seems like that mod is suffering from a similar issue (only neoforge and fabric is supported) i hope this gets fixed too because i don't like neoforge i hate it

**Comment by ToCraft** [comment]
I think I'll have to drop 1.20.6 Forge for now, maybe I'm able to re-add it at some future date.
