### ISSUE TITLE
Crash on startup for newest update

### ISSUE THREAD

**Issue by ReeCodes** [ToCraft/craftedcore#14]
### Mod loader

Forge

### Minecraft version

1.20.1

### CraftedCore version

craftedcore-4.2.4.1-forge

### Modloader version

Forge - 47.3.1

### The latest.log file

https://mclo.gs/7uYpvqW

### Issue description

Crash on startup

**Comment by ToCraft** [comment]
Fixed as of 424ec2202f7f592a19b0cd7e7b2606e268c591ed (CraftedCore 4.3.1).
