### ISSUE TITLE
Fabric version crashes on launch

### ISSUE THREAD

**Issue by jakeismyname** [ToCraft/craftedcore#16]
### Mod loader

Fabric

### Minecraft version

1.21

### CraftedCore version

5.0

### Modloader version

0.16.0

### The latest.log file

https://mclo.gs/2d3H6fn

### Issue description

Looks to be trying to load classes specific to the NeoForge version of CraftedCore. NeoForge version launches fine.

**Comment by ToCraft** [comment]
fixed as of 5.1
