### ISSUE TITLE
"Exit Code 1" Error after August 2 update

### ISSUE THREAD

**Issue by lookitsjoshy** [ToCraft/craftedcore#18]
### Mod loader

Forge

### Minecraft version

1.20.1

### CraftedCore version

1.20.1-forge-5.1

### Modloader version

47.2.0

### The latest.log file

[latest.log](https://github.com/user-attachments/files/16486464/latest.log)

### Issue description

Crafted Core 5.1, updated August 2, is causing 1.20.1 Minecraft, launched through Forge 47.2.0, to crash and report an Exit Code 1 error. When I reinstalled a previous version of Crafted Core (5), game proceeded to start and run as normal.

Removing only this mod (and any mods that depend on it) resolves the crashing issue. The only other mod I have that depends on Crafted Core is Wood Walkers, whose most recent version was uploaded mid July and which I updated to in late July. Game launched fine on August 1, but upon updating Crafted Core and trying to play on August 3, the error proceeded to occur until I reinstalled to an older version of Crafted Core.

### Steps to reproduce

1. Have Crafted Core 5.1 for Forge 47.2.0 and Minecraft 1.20.1 installed
2. Start Minecraft through Forge and then official launcher
3. Game attempts to load, then crashes and reports Exit Code 1 error

**Comment by ToCraft** [comment]
*should* be fixed as of 1.20.1-forge-5.1.0.1
