### ISSUE TITLE
Mixin Issue causes server crash on 1.20.1

### ISSUE THREAD

**Issue by seancrain** [ToCraft/craftedcore#19]
### Mod loader

Forge

### Minecraft version

1.20.1

### CraftedCore version

5.1

### Modloader version

47.3.5

### The latest.log file

[latest.log](https://github.com/user-attachments/files/16488606/latest.log)

### Issue description

Attempting to start the server involves a mixin failure that seems to implicate the MinecraftServerMixin. I am running this server in an environment with the Sinytra Connector mod which allows Fabric mods to run on Forge (there are no actual Fabric mods running server-side, they're only there because the client uses them for Continuity and Fabric Skyboxes, which have no Forge equivalents as far as I know). I don't know if Connector has anything to do with this but I certainly wouldn't rule it out.

It seems to indicate that the onServerCrash() method does not exist, and thus cannot inject anything.

This issue is not present in 4.x versions of CraftedCore. 

### Steps to reproduce

1. Install mod on server
2. Run server
3. Get mixin error

Possibly need Connector installed to produce issue, may have to report this to [https://github.com/Sinytra/Connector/issues](https://github.com/Sinytra/Connector/issues).

### Other

Connector

**Comment by ToCraft** [comment]
*should* be fixed as of 1.20.1-forge-5.1.0.1
