### ISSUE TITLE
Update message on login cannot be disabled

### ISSUE THREAD

**Issue by katubug** [ToCraft/craftedcore#2]
Hi, I'm using version 1.3.1 on Minecraft 1.20.1, and every time I log in, I get notified that "A new version of CraftedCore is available: 2."

However, there is no newer version listed on Curseforge, and I cannot find a config to disable this message. Is this something you could add? Thank you!

**Comment by ToCraft** [comment]
Yeah, I'm aware of that issue, it's caused since the development version is taken into account in the version checker, too. I've already changed the way it works though I'll implementd a config to disable it, too.
