### ISSUE TITLE
Mixin error causing crash on fabric 1.20.1

### ISSUE THREAD

**Issue by Dragunsblood** [ToCraft/craftedcore#20]
### Mod loader

Fabric

### Minecraft version

1.20.1

### CraftedCore version

5.1

### Modloader version

Fabric 1.20.1

### The latest.log file

[latest.log](https://github.com/user-attachments/files/16502786/latest.log)

### Issue description

craftedcore is causing game to fail to launch

**Comment by Pomfe** [comment]
I can attest to this

**Comment by ToCraft** [comment]
There was some error in the uploading task. I've uploaded a fix as of 5.1.0.1. Forge 1.20.1 should be fixed, too. I'm not sure about the other versions...
