### ISSUE TITLE
add mod menu support (fabric mod)

### ISSUE THREAD

**Issue by Find4U2Go2** [ToCraft/craftedcore#21]
### Describe your idea, include images if necessary

that way you can change the config in-game with mod menu and have it automatically updated

**Comment by ToCraft** [comment]
Hey! I've not only just [added support for mod menu](https://github.com/ToCraft/craftedcore/commit/5a718126c1ddddb66dfa46fcb6c9a49a7936a978), but also for the mod list in Minecraft Forge and NeoForge.
You need to install Cloth Config API, if you want to use the new config screen.
