### ISSUE TITLE
Connection Lost in a Singleplayer World.

### ISSUE THREAD

**Issue by DominusVulp** [ToCraft/craftedcore#22]
### Mod loader

Forge

### Minecraft version

1.20.4

### CraftedCore version

5.6

### Modloader version

49.1.13

### The latest.log file

Internal Exception: java.lang.NullPointerException: Cannot invoke "tocraft.craftedcore.network.ModernNetworking$Receiver.receive(tocraft.c raftedcore.network.ModernNetworking$Context, net.minecraft.nbt.CompoundTag)" because "receiver" is null

### Issue description

This error shows up when i try to enter my singleplayer world. The error shows up soon the world loads in.

### Steps to reproduce

1. Start The Game with OptiFine_1.20.4_HD_U_I7 and craftedcore-5.6 instaled
2. Go into your singleplayer world.

### Other

This issue just appears when i try to use the Craftedcore alongside with Optifine. When i removed optifine, the error stops showing up.

**Comment by ToCraft** [comment]
Did you install any other mods? I just tested it and nothing went wrong...

**Comment by ToCraft** [comment]
closed due to lack of response. will be reopened upon response
