### ISSUE TITLE
World Closing on MP & SP Modpack

### ISSUE THREAD

**Issue by 00J1NX00** [ToCraft/craftedcore#23]
### Mod loader

Forge

### Minecraft version

1.20.1

### CraftedCore version

5.6

### Modloader version

47.3.12 (Also tested on 47.2.32)

### The latest.log file

[latest.log](https://github.com/user-attachments/files/17875179/latest.log)

### Issue description

Using lateset versions of CraftedCore, Woodwalkers, & Remorphed. World closes after loading, citing error: java.lang.NullPointerException: Cannot invoke "tocraft.craftedcore.config.Config.getClass()" because "serverConfig" is null

Mod _was_ working fine on singleplayer. First encountered this error when my friend joined the world, using Essential 1.3.5.3. Since then, the issue persists on both singleplayer and multiplayer.

### Steps to reproduce

1. Install listed mods, use Essential mod for MP
2. Host world and wait for another player to join
3. Crash
4. Load the world in singleplayer
5. Crash

### Other

Could potentially be an incompatibility with another mod, given the size of the modpack; though trial and error mod testing has yielded no result, this seems to be a persistent issue regardless of loaded mods.

**Comment by ToCraft** [comment]
Hey! Please check your `config/craftedcore.json5` file. If it's empty or just contains `null`, delete it. Let me know if it worked!
I've also just written a small fix for it (3ac162df17e757ba2150c003d74668dda9897784), but I can't test it because I currently don't have access to my alt account

**Comment by 00J1NX00** [comment]
The `config/craftedcore.json5` file isn't empty, nor does it contain `null`. I can't test the fix you've written because it's not accessible in a `.jar` file. This is what's in my `config/craftedcore.json5` file, if you'd like to look over it; it looks pretty normal to me.

```
{
  // Toggle the version checking for every mod that uses CraftedCore
  "enableVersionChecking": true,
  // Update cached Player Profiles in the background
  "autoUpdateCache": true
}

**Comment by ToCraft** [comment]
Actually, you can download a ZIP file with all the JAR mod files via the linked commit: https://github.com/ToCraft/craftedcore/actions/runs/12094478999
It's listed in the "Artifacts" section.

**Comment by 00J1NX00** [comment]
Using the new 5.7 fix, it did the same thing; disconnected me from the world. This time, however, it gave me a different error:

`java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null`

I can provide the full log if required.

**Comment by ToCraft** [comment]
Yep, I'll need the full log to find the issue. Feel free to use sites like [mclo.gs](https://mclo.gs) to black out sensitive data (e.g. usernames).

**Comment by 00J1NX00** [comment]
Here's the log file.

[latest_censored.log](https://github.com/user-attachments/files/17995072/latest_censored.log)

**Comment by ToCraft** [comment]
Alright. It seems like Essentials is blocking the network package of craftedcore (it seems to have limited the package size but craftedcore needs to send some the config values). Please report this issue to essentials.
