### ISSUE TITLE
Crash with Patchouli on startup?

### ISSUE THREAD

**Issue by border999** [ToCraft/craftedcore#3]
![Screenshot 2024-02-01 130318](https://github.com/ToCraft/craftedcore/assets/11824584/e588a456-7eaa-4bd3-a3eb-8c2f9addbf53)
![Screenshot 2024-02-01 130340](https://github.com/ToCraft/craftedcore/assets/11824584/dde6c399-cd0b-4af8-8cb1-e829531cc66e)

**Comment by ToCraft** [comment]
You're using a old version of craftedcore (or one of my other mods, e.g. woodwalkers). Please update them and install Architectury API.
