### ISSUE TITLE
Config corruption prevents users logging into server

### ISSUE THREAD

**Issue by katubug** [ToCraft/craftedcore#4]
Hi! I was trying to connect to my modded server and was unable to log in due to craftedcore config being "null." I was able to resolve the issue by deleting the craftedcore.json, but this is the second or third time it's happened so I figured it was worth reporting.

Here is the server's latest.log and debug.log:
[latest.log](https://github.com/ToCraft/craftedcore/files/14272448/latest.log)
[debug.log](https://github.com/ToCraft/craftedcore/files/14272449/debug.log)

I'm using CraftedCore 2.1 on Forge 47.2.20 for Minecraft 1.20.1.

Thanks for your time!

**Comment by ToCraft** [comment]
Could you send me your client logs?

**Comment by katubug** [comment]
Here's my client log, but I want to add 2 caveats: 1) I checked my log for information when I was trying to figure out what was going wrong, and I didn't see anything that seemed helpful. And 2) I'm not 100% sure this is the right log, although I am fairly certain it is.

[latest.log](https://github.com/ToCraft/craftedcore/files/14284473/latest.log)

**Comment by ToCraft** [comment]
Well, I'm not 100% sure (I've never encountered this error), but it should be fixed as of 131abd679860ca34ed06bb0a6417c5b2bf8f6ae8. If the error still occurs, you can reopen this issue. The change will be available with the next update.

**Comment by ToCraft** [comment]
Alright, I just tested it on diffrent modloader, and the reason I didn't encounter the problem was, that it doesn't occur on Fabric and I mainly tested on Fabric. Moreover, I definitely fixed it as of 253270ad832105b1ce1dbe2ca6641d0f986cf59d. :D
