### ISSUE TITLE
Versions above 3.1.1 cause multiplayer server startup crash

### ISSUE THREAD

**Issue by katubug** [ToCraft/craftedcore#6]
### Mod loader

Forge

### Minecraft version

1.20.1

### CraftedCore version

3.2.1

### Modloader version

47.2.20

### The latest.log file

https://gist.github.com/katubug/ab17532f15ec3578e1207110ede7e4a2

### Issue description

When attempting to load a server with more recent updates of CraftedCore, Remorphed, and Woodwalkers, the mods fail to build. I'm not sure if this is a recently introduced incompatibility with some of my other mods (the crash report indicates Sinytra Connector, which was not previously an issue), or what?

Everything works hunky dory in singleplayer, it's only on a multiplayer server that I'm having issues. Rolling back to the following versions works correctly on servers:
- CraftedCore 3.1.1
- Remorphed 3.2
- Woodwalkers 3.0

It seems if I update any of them to more recent versions, the issue occurs - but I haven't done rigorous testing.

### Steps to reproduce

Load up multiplayer server with latest versions of CraftedCore, Woodwalkers, Remorphed.

**Comment by ToCraft** [comment]
Looks like the server is missing a background library. I'll upload a fix tomorrow (that implements the library into the mod)
