### ISSUE TITLE
Cannot sleep while CraftedCore 4.1 is installed

### ISSUE THREAD

**Issue by brentmaas** [ToCraft/craftedcore#8]
### Mod loader

Fabric

### Minecraft version

1.20.1

### CraftedCore version

4.1

### Modloader version

0.15.11

### The latest.log file

[latest.log](https://github.com/ToCraft/craftedcore/files/15327176/latest.log)

### Issue description

Sleeping is not possible on both singleplayer and multiplayer. Spawn points will be set, though. This includes modded ways of sleeping, like sleeping bags. An attempt to sleep is accompanied by a stacktrace in latest.log.

### Steps to reproduce

1. Join a world on either singleplayer or multiplayer
2. Try to sleep in a bed during the night

### Other

The latest versions (as of writing) of Fabric, Fabric API, Architectury and CraftedCore for Minecraft 1.20.1 were installed. Disabling CraftedCore allows the player to sleep again. I noticed in a changelog that CraftedCore implemented player sleep events, so I would guess it's related to that.

**Comment by ToCraft** [comment]
fixed as of 9c30c59740534752ea60fe19b473fc1b6271facb

**Comment by brentmaas** [comment]
Great, thank you!
